# -*- coding: utf-8 -*-
"""ProductReview_Week3_ShikderRasel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJ5uE-4ACn1coMST4z5OV0jpzKmv1gkE
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

df = pd.read_csv('/content/drive/MyDrive/AI ML Bootcamp/Week 1/product_reviews.csv')
df.head()

df['new_col'] = df['Sentiment'].apply(lambda x: 2 if x == 'Positive' else (1 if x == 'Neutral' else 0))

df.head()

df['Sentiment'].value_counts()

mapping = {
    'Positive': 1,
    'Negative': 2,
    'Neutral': 0
}
df['Predictor'] = df['Sentiment'].map(mapping)

df.dtypes

X_train, X_test, y_train, y_test = train_test_split(df['Review'], df['new_col'], test_size=0.30)

cv = CountVectorizer()
X_train_count = cv.fit_transform(X_train.values)

model = MultinomialNB()
model.fit(X_train_count, y_train)

email_not_spam = ["Hello, bro!"]
email_not_spam_count = cv.transform(email_not_spam)
model.predict(email_not_spam_count)

email_spam = ["Great opportunity to win prize!"]
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

positive=['The product is so good. I will order it next time']
negative=['The product is worse. it small dirty and packed poorly']
neutral=['The product is average']

print(model.predict(cv.transform(positive)))
print(model.predict(cv.transform(negative)))
print(model.predict(cv.transform(neutral)))

X_test_count = cv.transform(X_test)
model.score(X_test_count, y_test)
y_pred = model.predict(X_test_count)
accuracy = (y_pred == y_test).mean()
print(accuracy)
precision = precision_score(y_test, y_pred, average='weighted')
print(precision)
recall = recall_score(y_test, y_pred, average='weighted')
print(recall)
f1 = f1_score(y_test, y_pred, average='weighted')
print(f1)

